version: "3.9"

services:
  fastapi:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "8484:8484"
    command: "uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8484 --reload"
    volumes:
      - "./app/src:/usr/src/app"
